In [1]:
import numpy as np

In [3]:
a_1dim = np.array([1, 2, 3])

In [4]:
a_1dim

array([1, 2, 3])

In [5]:
a_2dim = np.array([[3, 4, 5],
                  [6, 7, 8]])

In [6]:
a_2dim

array([[3, 4, 5],
       [6, 7, 8]])

In [9]:
a_3dim = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                  [10, 11, 12]]])

In [10]:
a_3dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
a_1dim.shape, a_1dim.dtype, a_1dim.size, type(a_1dim)

((3,), dtype('int64'), 3, numpy.ndarray)

In [18]:
a_2dim.shape, a_2dim.dtype, a_2dim.size, type(a_2dim)

((2, 3), dtype('int64'), 6, numpy.ndarray)

In [19]:
a_3dim.shape, a_3dim.dtype, a_3dim.size, type(a_3dim)

((2, 2, 3), dtype('int64'), 12, numpy.ndarray)

In [20]:
import pandas as pd

In [23]:
a2 = pd.DataFrame(a_2dim)
a2

0  1  2
0  3  4  5
1  6  7  8

In [25]:
ones_array = np.ones((10, 2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
zeros_array = np.zeros((7, 2, 3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [33]:
randints = np.random.randint(0, 10, (7, 2))
randints

array([[1, 0],
       [0, 9],
       [9, 5],
       [5, 6],
       [0, 6],
       [6, 1],
       [5, 4]])

In [43]:
randfloats = np.random.rand(3, 5)
randfloats

array([[0.08363959, 0.52144524, 0.84150816, 0.97810465, 0.77649092],
       [0.37944035, 0.53609352, 0.00362796, 0.09948085, 0.36834023],
       [0.0617081 , 0.91016574, 0.0927052 , 0.87647309, 0.92874473]])

In [46]:
np.random.seed(42)
randints2 = np.random.randint(0, 10, (4, 6))
randints2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [69]:
randints3 = np.random.randint(1, 10, (3, 7))
randints3

array([[6, 4, 7, 9, 7, 1, 1],
       [9, 9, 4, 9, 3, 7, 6],
       [8, 9, 5, 1, 3, 8, 6]])

In [48]:
np.unique(randints3)

array([1, 2, 3, 4, 5, 7, 9])

In [57]:
randints3[0, 0]

9

In [59]:
randints3[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [60]:
randints3[:2, :2]

array([[9, 1],
       [5, 3]])

In [71]:
randints4 = np.random.randint(0, 10, (3, 5))
ones_3x5 = np.ones((3, 5))

In [75]:
addition = randints4 + ones_3x5
addition

array([[ 8.,  9.,  4.,  1.,  1.],
       [10.,  4.,  7.,  2.,  3.],
       [ 1.,  5.,  1.,  8.,  1.]])

In [78]:
ones_5x3 = np.ones((5, 3))

In [81]:
addition2 = addition + ones_5x3.T
addition2

array([[ 9., 10.,  5.,  2.,  2.],
       [11.,  5.,  8.,  3.,  4.],
       [ 2.,  6.,  2.,  9.,  2.]])

In [88]:
latest = addition2 - ones_3x5
latest

array([[ 8.,  9.,  4.,  1.,  1.],
       [10.,  4.,  7.,  2.,  3.],
       [ 1.,  5.,  1.,  8.,  1.]])

In [94]:
latest = latest * ones_3x5
latest

array([[4.096e+03, 6.561e+03, 2.560e+02, 1.000e+00, 1.000e+00],
       [1.000e+04, 2.560e+02, 2.401e+03, 1.600e+01, 8.100e+01],
       [1.000e+00, 6.250e+02, 1.000e+00, 4.096e+03, 1.000e+00]])

In [96]:
latest ** 2

array([[1.6777216e+07, 4.3046721e+07, 6.5536000e+04, 1.0000000e+00,
        1.0000000e+00],
       [1.0000000e+08, 6.5536000e+04, 5.7648010e+06, 2.5600000e+02,
        6.5610000e+03],
       [1.0000000e+00, 3.9062500e+05, 1.0000000e+00, 1.6777216e+07,
        1.0000000e+00]])

In [97]:
np.square(latest)

array([[1.6777216e+07, 4.3046721e+07, 6.5536000e+04, 1.0000000e+00,
        1.0000000e+00],
       [1.0000000e+08, 6.5536000e+04, 5.7648010e+06, 2.5600000e+02,
        6.5610000e+03],
       [1.0000000e+00, 3.9062500e+05, 1.0000000e+00, 1.6777216e+07,
        1.0000000e+00]])

In [98]:
np.mean(latest)

1892.8666666666666

In [99]:
# skip to dot products

In [103]:
array1 = np.random.randint(0, 10, (3, 3))
array2 = np.random.randint(0, 10, (3, 2))

In [104]:
array1

array([[5, 0, 8],
       [5, 2, 3],
       [3, 2, 9]])

In [105]:
array2

array([[2, 2],
       [3, 6],
       [3, 8]])

In [106]:
array1.dot(array2)

array([[34, 74],
       [25, 46],
       [39, 90]])

In [107]:
array2.dot(array1)

ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [108]:
array3 = np.random.randint(0, 10, (4, 3))
array4 = np.random.randint(0, 10, (4, 3))

In [109]:
array3

array([[0, 7, 6],
       [1, 7, 0],
       [8, 8, 1],
       [6, 9, 2]])

In [114]:
array3.T

array([[0, 1, 8, 6],
       [7, 7, 8, 9],
       [6, 0, 1, 2]])

In [110]:
array4

array([[6, 9, 8],
       [3, 0, 1],
       [0, 4, 4],
       [6, 8, 8]])

In [113]:
array4.T

array([[6, 3, 0, 6],
       [9, 0, 4, 8],
       [8, 1, 4, 8]])

In [112]:
array3.dot(array4.T)

array([[111,   6,  52, 104],
       [ 69,   3,  28,  62],
       [128,  25,  36, 120],
       [133,  20,  44, 124]])

In [115]:
array4.dot(array3.T)

array([[111,  69, 128, 133],
       [  6,   3,  25,  20],
       [ 52,  28,  36,  44],
       [104,  62, 120, 124]])

In [134]:
array5 = np.random.randint(0, 10, (3, 5))
array6 = np.random.randint(0, 10, (3, 5))

In [135]:
array5

array([[5, 7, 1, 4, 0],
       [0, 4, 2, 3, 2],
       [0, 0, 4, 5, 2]])

In [136]:
array6

array([[8, 4, 7, 0, 4],
       [2, 0, 3, 4, 6],
       [0, 2, 1, 8, 9]])

In [120]:
array5 > array6

array([[False, False,  True, False,  True],
       [False,  True,  True,  True, False],
       [ True, False, False, False, False]])

In [121]:
array5 >= array6

array([[False, False,  True, False,  True],
       [False,  True,  True,  True, False],
       [ True, False, False, False, False]])

In [122]:
array5 > 7

array([[False, False,  True, False,  True],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [123]:
array5 == array6

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [124]:
np.sort(array6)

array([[3, 4, 6, 7, 7],
       [0, 0, 2, 2, 5],
       [2, 5, 5, 5, 6]])

In [125]:
np.argsort(array6)

array([[1, 0, 4, 2, 3],
       [1, 2, 0, 3, 4],
       [4, 1, 2, 3, 0]])

In [138]:
array6

array([[8, 4, 7, 0, 4],
       [2, 0, 3, 4, 6],
       [0, 2, 1, 8, 9]])

In [137]:
array5

array([[5, 7, 1, 4, 0],
       [0, 4, 2, 3, 2],
       [0, 0, 4, 5, 2]])

In [139]:
np.argmax(array6)

14

In [140]:
np.argmax(array5)

1

In [142]:
np.argmax(array6, axis=0)

array([0, 0, 0, 2, 2])

In [143]:
np.argmax(array6, axis=1)

array([0, 4, 4])

In [144]:
np.random.normal()

0.173180925851182

In [145]:
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [149]:
np.random.randn(1, 7)

array([[ 0.65139125, -0.31526924,  0.75896922, -0.77282521, -0.23681861,
        -0.48536355,  0.08187414]])